server:
  port: 9001
spring:
  application:
    name: idecide-base  #为当前项目取名字,注意yml不要写’_‘ 要改成 ’-‘
#eureka:
#  client:
#    service-url:
#      defaultZone: http://127.0.0.1:6868/eureka #服务发现的地址
#  instance:
#    prefer-ip-address: true   #写上这个之后，不同模块之间可以跨域访问！